[build.environment]
  PYTHON_VERSION = "3.11"

[build]
  # Upgrade packaging tools first, then install your deps, then run your frontend build
  command = "python -m pip install --upgrade pip setuptools wheel && python -m pip install -r requirements.txt && npm run build"
  publish = "dist"
